export const AllPossibleIngredients = [
    "abalone",
    "acorn squash",
    "adobo sauce",
    "agave nectar",
    "ahi tuna",
    "alfalfa sprouts",
    "alligator",
    "almond extract",
    "almonds",
    "amaretto",
    "anchovies",
    "andouille sausage",
    "angel hair pasta",
    "angostura bitters",
    "apple brandy",
    "apple cider",
    "apple juice",
    "apple pie spice",
    "apricot",
    "apricot jam",
    "aquavit",
    "arborio rice",
    "artichoke hearts",
    "arugula",
    "asiago cheese",
    "asparagus",
    "avocado",
    "bacon",
    "baking powder",
    "baking soda",
    "balsamic vinegar",
    "bamboo shoots",
    "banana",
    "barbecue sauce",
    "barley",
    "basil",
    "bay leaves",
    "beans",
    "beef",
    "beef broth",
    "beef consommé",
    "beef jerky",
    "beer",
    "beets",
    "bell peppers",
    "berries",
    "bittersweet chocolate",
    "black beans",
    "black olives",
    "black pepper",
    "blackberries",
    "blue cheese",
    "blueberries",
    "bok choy",
    "bourbon",
    "brandy",
    "Brazil nuts",
    "bread",
    "breadcrumbs",
    "brie cheese",
    "broccoli",
    "brown rice",
    "brown sugar",
    "brussels sprouts",
    "bulgur",
    "butter",
    "buttermilk",
    "butterscotch chips",
    "cabbage",
    "caesar dressing",
    "cajun seasoning",
    "cake mix",
    "candied ginger",
    "cane syrup",
    "cantaloupe",
    "capers",
    "caramel",
    "caraway seeds",
    "cardamom",
    "carp",
    "carrots",
    "cashews",
    "catfish",
    "cayenne pepper",
    "celery",
    "celery seed",
    "champagne",
    "chard",
    "cheddar cheese",
    "cheese",
    "cherries",
    "cherry brandy",
    "cherry pie filling",
    "chervil",
    "chestnuts",
    "chia seeds",
    "chicken",
    "chicken broth",
    "chicken livers",
    "chicken stock",
    "chickpeas",
    "chili paste",
    "chili peppers",
    "chili powder",
    "chocolate",
    "chocolate chips",
    "chocolate syrup",
    "chorizo",
    "cilantro",
    "cinnamon",
    "cinnamon stick",
    "clams",
    "clove",
    "clover honey",
    "cocoa powder",
    "coconut",
    "coconut milk",
    "cod",
    "coffee",
    "cognac",
    "cointreau",
    "coleslaw dressing",
    "collard greens",
    "confectioners sugar",
    "cookie crumbs",
    "coriander",
    "corn",
    "corn bread mix",
    "corn chips",
    "corn syrup",
    "corned beef",
    "cornish hens",
    "cottage cheese",
    "country ham",
    "courgette",
    "couscous",
    "crab",
    "crabmeat",
    "cracked pepper",
    "cranberries",
    "cranberry juice",
    "cream",
    "cream cheese",
    "cream of chicken soup",
    "cream of mushroom soup",
    "cream of tartar",
    "creamed corn",
    "cremini mushrooms",
    "creole seasoning",
    "croutons",
    "crystallized ginger",
    "cucumber",
    "cumin",
    "currants",
    "curry",
    "daikon",
    "dark chocolate",
    "dates",
    "deep dish pie crust",
    "deli ham",
    "dessert shells",
    "dill",
    "dill pickles",
    "dijon mustard",
    "double cream",
    "dried cherries",
    "dried cranberries",
    "dried oregano",
    "dried porcini mushrooms",
    "dried thyme",
    "dry bread crumbs",
    "dry sherry",
    "dry vermouth",
    "duck",
    "dulce de leche",
    "edamame",
    "egg roll wraps",
    "eggplant",
    "eggs",
    "elbow macaroni",
    "enchilada sauce",
    "english muffin",
    "fennel",
    "fennel seeds",
    "fenugreek seeds",
    "feta cheese",
    "figs",
    "filet mignon",
    "fish sauce",
    "flank steak",
    "flax seeds",
    "flour",
    "fontina cheese",
    "food coloring",
    "frankfurters",
    "free-range eggs",
    "french bread",
    "fresh basil",
    "fresh parsley",
    "fresh spinach",
    "fresh thyme",
    "fried rice",
    "frosting",
    "fruit cocktail",
    "fruit preserves",
    "fudge topping",
    "garam masala",
    "garbanzo beans",
    "garlic",
    "garlic powder",
    "gelatin",
    "gin",
    "ginger",
    "ginger ale",
    "ginger beer",
    "gingerroot",
    "gjetost cheese",
    "gnocchi",
    "goat cheese",
    "golden raisins",
    "gouda cheese",
    "graham cracker crumbs",
    "graham cracker pie crust",
    "graham crackers",
    "grain alcohol",
    "grand marnier",
    "grapefruit",
    "grapefruit juice",
    "grapes",
    "grapeseed oil",
    "green beans",
    "green bell pepper",
    "green chili pepper",
    "green food coloring",
    "green grapes",
    "green olives",
    "green onions",
    "green pepper",
    "green tea bags",
    "grits",
    "ground beef",
    "ground chicken",
    "ground cinnamon",
    "ground cumin",
    "ground ginger",
    "ground pork",
    "ground turkey",
    "guava",
    "habanero pepper",
    "haddock",
    "hamburger buns",
    "heavy cream",
    "herring",
    "hoisin sauce",
    "honey",
    "honeydew melon",
    "horseradish",
    "hot chocolate mix",
    "hot mustard",
    "hot sauce",
    "hummus",
    "ice",
    "ice cream",
    "iceberg lettuce",
    "icing",
    "instant coffee",
    "instant noodles",
    "instant pudding mix",
    "irish cream",
    "italian dressing",
    "italian seasoning",
    "jalapeno",
    "jamaican jerk seasonings",
    "jelly",
    "jicama",
    "jimmies",
    "juice",
    "kale",
    "ketchup",
    "kidney beans",
    "kiwi",
    "kosher salt",
    "ladyfingers",
    "lamb",
    "lasagna noodles",
    "lean ground beef",
    "lean ground turkey",
    "leeks",
    "lemon curd",
    "lemon juice",
    "lemongrass",
    "lentils",
    "lettuce",
    "light cream",
    "light mayonnaise",
    "light soy sauce",
    "lime",
    "lime juice",
    "lime wedges",
    "limoncello",
    "linguine",
    "liquid smoke",
    "lobster",
    "long-grain rice",
    "low-fat buttermilk",
    "low-fat milk",
    "low-fat plain yogurt",
    "low-fat ricotta cheese",
    "low-sodium chicken broth",
    "low-sodium soy sauce",
    "lump crabmeat",
    "macadamia nuts",
    "macaroni",
    "malt vinegar",
    "mandarin oranges",
    "mango",
    "maple syrup",
    "margarine",
    "marinara sauce",
    "marjoram",
    "marsala wine",
    "marshmallow fluff",
    "marshmallows",
    "mascarpone",
    "matzo",
    "mayonnaise",
    "meat",
    "meatballs",
    "medjool dates",
    "melon liqueur",
    "melted butter",
    "meringue powder",
    "mesclun",
    "milk",
    "mint",
    "mint extract",
    "mint jelly",
    "monterey jack cheese",
    "mozzarella cheese",
    "mushrooms",
    "mussels",
    "mustard",
    "mustard seeds",
    "napa cabbage",
    "navel oranges",
    "nectarine",
    "nori",
    "nutmeg",
    "nutritional yeast",
    "oat bran",
    "oats",
    "oil",
    "okra",
    "old bay seasoning",
    "olive oil",
    "onion",
    "onion powder",
    "orange",
    "orange juice",
    "orange liqueur",
    "orange marmalade",
    "orange zest",
    "oregano",
    "orzo pasta",
    "oysters",
    "palm sugar",
    "pancetta",
    "paneer",
    "panko bread crumbs",
    "papaya",
    "paprika",
    "parmesan cheese",
    "parsley",
    "passion fruit",
    "pasta",
    "pasta sauce",
    "peach",
    "peanut butter",
    "peanut oil",
    "peanuts",
    "pear brandy",
    "pear liqueur",
    "pears",
    "peas",
    "pecan",
    "penne pasta",
    "pepper",
    "peppermint extract",
    "pepperoni",
    "pesto",
    "pickle relish",
    "pickles",
    "pico de gallo",
    "pimientos",
    "pine nuts",
    "pineapple",
    "pineapple juice",
    "pink beans",
    "pinto beans",
    "pistachio nuts",
    "pita bread",
    "pizza crust",
    "pizza sauce",
    "plum",
    "plum tomatoes",
    "poblano peppers",
    "polenta",
    "Ponzu sauce",
    "popcorn",
    "poppy seeds",
    "pork",
    "pork chops",
    "pork ribs",
    "port wine",
    "portobello mushrooms",
    "pot roast",
    "potato chips",
    "potatoes",
    "poultry seasoning",
    "powdered sugar",
    "prosciutto",
    "provolone cheese",
    "prunes",
    "pumpkin",
    "pumpkin pie spice",
    "pumpkin puree",
    "pumpkin seeds",
    "queso fresco",
    "quinoa",
    "rabbit",
    "rack of lamb",
    "radicchio",
    "radishes",
    "raisins",
    "ramen noodles",
    "raspberries",
    "ravioli",
    "red bell pepper",
    "red cabbage",
    "red chili flakes",
    "red grapes",
    "red kidney beans",
    "red lentils",
    "red onion",
    "red pepper flakes",
    "red potatoes",
    "red snapper",
    "red wine",
    "red wine vinegar",
    "relish",
    "rib eye steak",
    "rice",
    "ricotta cheese",
    "ritz crackers",
    "roast beef",
    "rolled oats",
    "romaine lettuce",
    "rosemary",
    "rotini pasta",
    "rum",
    "rutabaga",
    "rye bread",
    "saffron",
    "sage",
    "sake",
    "salad dressing",
    "salmon",
    "salsa",
    "salt",
    "sambuca",
    "sausage",
    "savory",
    "scallops",
    "scotch",
    "sea bass",
    "sea salt",
    "seitan",
    "sesame oil",
    "sesame seeds",
    "shallots",
    "sherry",
    "shiitake mushrooms",
    "shortening",
    "shrimp",
    "sirloin steak",
    "skim milk",
    "sliced almonds",
    "smoked salmon",
    "smoked sausage",
    "smoothie mix",
    "snapper",
    "soba noodles",
    "soda water",
    "sour cream",
    "sourdough bread",
    "soy milk",
    "soy sauce",
    "spaghetti",
    "spaghetti squash",
    "spanish rice",
    "spelt",
    "spicy brown mustard",
    "spinach",
    "spring roll wrappers",
    "sprouts",
    "squash",
    "squid",
    "sriracha",
    "steak",
    "steak sauce",
    "steel cut oats",
    "stew meat",
    "strawberries",
    "strawberry jam",
    "strawberry preserves",
    "sugar snap peas",
    "sultanas",
    "sumac",
    "sun-dried tomatoes",
    "sweet potatoes",
    "swiss chard",
    "swiss cheese",
    "swordfish",
    "tahini",
    "tamarind",
    "tangerines",
    "tapioca",
    "tarragon",
    "teff",
    "tempeh",
    "tequila",
    "thyme",
    "tilapia",
    "tofu",
    "tomatillos",
    "tomato paste",
    "tomato sauce",
    "tomato soup",
    "tortellini",
    "tortillas",
    "triticale",
    "trout",
    "turkey",
    "turmeric",
    "turnips",
    "turpentine",
    "udon noodles",
    "uni (sea urchin)",
    "urad dal",
    "vanilla beans",
    "vanilla extract",
    "veal",
    "vegan cheese",
    "vegan mayo",
    "vegan milk",
    "vegan yogurt",
    "vegetable broth",
    "vegetable oil",
    "venison",
    "vermicelli noodles",
    "vermouth",
    "verrines",
    "vinaigrette",
    "vinegar",
    "vodka",
    "walnuts",
    "wasabi",
    "water chestnuts",
    "watercress",
    "watermelon",
    "wheat bran",
    "wheat germ",
    "whiskey",
    "white chocolate",
    "white pepper",
    "white wine",
    "whole wheat flour",
    "wild rice",
    "wonton wrappers",
    "wraps",
    "yams",
    "yeast",
    "yellow squash",
    "yogurt",
    "yucca",
    "yuzu",
    "zest (lemon, orange)",
    "zinfandel wine",
    "ziti",
    "zucchini",
  ];
